messages:
  prefix: "&f[&6gAbility&f] "
  plugin_enabled: "&ahas been enabled :D!"
  plugin_disabled: "&chas been disabled, bye!"
  plugin_reloaded: "&ahas been reloaded!"
  new_plugin_version_available: "&aThere's a new version available :D! (%current_version% -> %new_version%) %repository%"
  no_permissions: "&cYou need (&7%missing_permissions%&c) permissions to do this"
  received_given_ability: "&aYou have received x%amount% %ability%"
  given_ability: "&a%player% has received x%amount% %ability%"
  global_item_cooldown: "&cYou're global item cooldown for %minutes%:%seconds%"
  item_cooldown: "&cYou're on %ability% &ccooldown for %minutes%:%seconds%"
abilities:
  global:
    cooldown: 10 #seconds
  strength:
    material_type: BLAZE_POWDER
    name: "&6Strength II"
    lore:
      - "&7Get Strength II for 5 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 90
    duration: 5 #seconds
    used_message: "&aYou have received &6Strength II &afor 5 seconds!"
    enchanted: true
  resistance:
    material_type: IRON_INGOT
    name: "&fResistance III"
    lore:
      - "&7Get Resistance III for 10 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 90
    duration: 10
    used_message: "&aYou have received &fResistance III &afor 10 seconds!"
    enchanted: true
  regeneration:
    material_type: GHAST_TEAR
    name: "&dRegeneration III"
    lore:
      - "&7Get Regeneration III for 5 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 90
    duration: 5
    used_message: "&aYou have received &dRegeneration III &afor 5 seconds!"
    enchanted: true
  switcher:
    material_type: SNOWBALL
    name: "&dSwitcher ball"
    lore:
      - "&7Switch places to whoever is hit from this projectile"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 30
    used_message: "&aYou have switched places with &e%target%&a!"
    target_message: "&cYou have switched places with &e%player%&c!"
    enchanted: true
  shrinker:
    material_type: BROWN_MUSHROOM
    name: "&cShrinker"
    lore:
      - "&7Reduces your size to half for 7 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 120
    duration: 7
    used_message: "&aYou have been shrunk to half your size for 7 seconds!"
    enchanted: true
  time_warp:
    material_type: FEATHER
    name: "&aTime Warp"
    lore:
      - "&7Teleport to your last thrown ender pearl in the past 20 seconds!"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 120
    duration: 20 #here the duration means the max amount of seconds the plugin will register the last ender pearl for
    used_message: "&aYou have used a Time Warp and will be teleported shortly..."
    error_message: "&cYou haven't thrown an ender pearl in the last 20 seconds..."
    enchanted: true
  reach:
    material_type: LEAD
    name: "&eReach"
    lore:
      - "&7Doubles your reach distance for 10 seconds!" #this also doubles reach for interacting with blocks
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 300
    duration: 10
    used_message: "&aYour reach has doubled for the next 10 seconds!"
    #this is useful if you want to stop false staff bans or false reports
    #if you want to turn this off, simply make it an empty string
    target_message: "&6%player% &chas used a &eReach Ability&c. They are able to hit further from normal for a few seconds"
    enchanted: true
  antitrap_bone:
    material_type: BONE
    name: "&6Anti-trap Bone"
    lore:
      - "&7Hit a player 3 times to prevent them interacting with blocks for 15 seconds!"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 120
    duration: 15
    used_message: "&aYou have hit %player% with an &6Anti-trap Bone&a, they won't be able to interact with blocks for 15 seconds"
    error_message: "&c%player% is currently under the effect of another &6Anti-trap Bone"
    target_message: "&cYou have been hit with an &6Anti-trap Bone&c, you're currently unable to interact with blocks"
    enchanted: true
  ninja_star:
    material_type: NETHER_STAR
    name: "&bNinja Star"
    lore:
      - "&7Teleport to the last player that hit you in the last 15 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 300
    duration: 15 #amount of seconds the plugin will register the last hit as valid
    used_message: "&aYou have used a &bNinja Star&a, you'll be teleported to &6%player% &ashortly"
    error_message: "&cYou haven't been hit in the last 15 seconds"
    target_message: "&6%player% &cused a &bNinja Star&c, they will be teleported to you shortly"
    enchanted: true
  combo:
    material_type: PUFFERFISH
    name: "&cCombo Ability"
    lore:
      - "&7When activated, every hit will give you half a second of Strength II"
      - "&7after 10 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 180
    duration: 10
    used_message: "&aYou have used a &cCombo Ability&a, every hit will get you half a second of Strength II for 10 seconds"
    enchanted: true
  confuser:
    material_type: APPLE
    name: "&cConfuser"
    lore:
      - "&7Hit a player 3 times to confuse them for 15 seconds,"
      - "&7on this state every block that they to place will"
      - "&7spawn a pig that will damage them instead"
      - "&7There's also a chance of a math question being shown to them"
      - "&7when activated, they won't be able to move until the question"
      - "&7gets solved"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 300
    duration: 15
    used_message: "&aYou have used a &cConfuser &aon %player%!"
    error_message: "&c%player% is currently under the effect of another &cConfuser"
    target_message: "&cYou have been hit with a Confuser!"
    enchanted: true
  focus_mode:
    material_type: GOLD_NUGGET
    name: "&eFocus Mode"
    lore:
      - "&7Gain an 25%% damage increase against the last player you hit in the last 15 seconds for 10 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 60
    duration: 10
    used_message: "&aYou have used a &eFocus Mode &aagainst %player%!"
    error_message: "&cYou haven't hit anyone in the last 15 seconds"
    target_message: "&6%player% &cused a &eFocus Mode &cagainst you, you will receive 25%% more damage from them"
    enchanted: true
  zeus_hammer:
    material_type: GOLDEN_AXE
    name: "&6Zeus Hammer"
    lore:
      - "&7Right click to activate a timer for 12 seconds in which every hit has a 25%%"
      - "&7chance of striking your opponent with a lightning"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 120
    duration: 10
    used_message: "&aYou have used a &6Zeus Hammer&a, every hit has a chance of striking your opponent"
    enchanted: true
  antitrap_beacon:
    #this item should be of one that can be placed
    #and one that cant be moved or broken by pistons
    #though this plugin will prevent this item from being broken or moved
    material_type: BEACON
    name: "&bAnti-trap Beacon"
    lore:
      - "&7Prevents any player from placing blocks in a radius of 15 blocks upon placing this beacon"
      - "&7This beacon can be destroyed by being hit 20 times or after 60 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 300
    duration: 60 #duration before the beacon automatically breaks
    used_message: "&aYou have used an &bAnti-trap Beacon&a, no player will be able to build in a radius of 15 blocks"
    target_message: "&cThere's an &bAnti-trap Beacon &cnearby, hit it 20 times to break it!"
    enchanted: true
  risky_mode:
    material_type: BRICK
    name: "&cRisky Mode"
    lore:
      - "&7Gives a damage boost depending on your HP"
      - "&7The lower your HP, the bigger the boost. Capped at 35%%"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 120
    duration: 10
    used_message: "&aYou have used a &cRisky Mode &aand have gained a %boost%%% damage boost" #e.g "20.5% damage boost"
    target_message: "&6%player% &cused a Risky Mode near you. They've got a damage boost for a few seconds"
    enchanted: true
  guardian_angel:
    material_type: CLOCK
    #when I first made ability items on skript long ago, I had a typo, "angle" instead of "angel"
    #it was pretty funny and I kept it
    #you should rename this to "angel" tho
    #this item prevents the player from dying once for a few seconds
    name: "&eGuardian Angle"
    lore:
      - #change this lol
      - "&7Right click to have a 30 second timer in which"
      - "&7the angle of the pythagorean theorem"
      - "&7hypotenuse of your health will be raised to the power"
      - "&7of the distance between 0 and 10 hearts"
      - ""
      - "&cCooldown: &7sqrt(8100) seconds."
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 90
    duration: 30
    used_message: "&aYou have used a &eGuardian Angle&a. For 30 seconds, you can't die!"
    error_message: "&cYour &eGuardian Angle &chas expired"
    target_message: "&aYour &eGuardian Angle &ahas saved you from death"
    enchanted: true
  rage_ball:
    material_type: EGG
    name: "&6Rage Ball"
    lore:
      - "&7Get Strength II and Resistance III for 7 seconds"
      - "&7and give everyone within a 10 block radius of where this projectile lands"
      - "&7Weakness II and Wither II for 7 seconds"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 300
    duration: 7
    used_message: "&aYou have used a &6Rage Ball &aand have gained Strength II and Resistance III for 7 seconds"
    target_message: "&6%player% &chas hit you with a &6Rage Ball&c. You've been debuffed for 7 seconds"
    enchanted: true
  portable_bard:
    material_type: BLAZE_SPAWN_EGG
    entity_type: SKELETON #this must be of a living entity (cows, skeletons... are valid, minecarts, items... are invalid)
    name: "&6Portable Bard"
    lore:
      - "&7Spawns an Skeleton which will give you passive bard effects when within 20 blocks of you:"
      - "&7Strength I, Resistance I, Regeneration I and Speed II"
      - "&7Occasionally, the Skeleton will give one a clickable bard effect for 5 seconds:"
      - "&7Strength II, Resistance III, Regeneration III or Speed III"
      - "&7The skeleton can be killed by being hit 20 times or after 60 seconds of being spawned"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 300
    duration: 60
    used_message: "&aYou have spawned a &6Portable Bard"
    enchanted: true
  starvation_flesh:
    material_type: ROTTEN_FLESH
    name: "&2Starvation Flesh"
    lore:
      - "&7Hit a player 3 times to set their hunger level to 0"
      - ""
      - "&dstore.mymcserver.com"
    cooldown: 120
    used_message: "&aYou have hit &6%player% &awith a &2Starvation Flesh"
    target_message: "&6%player% &chas hit you &cwith a &2Starvation Flesh"
    enchanted: true